//! JavBus 分类硬编码查找表
//!
//! 从 https://www.javbus.com/genre 和 https://www.javbus.com/uncensored/genre 提取。
//! 按 JavBus 页面的大类别分组（主題/角色/服裝/體型/行為/玩法/類別/其他/場景）。
//!
//! 对内提供 `lookup_genre_source_id` 快速查 source_id；
//! 对外提供 `all_genre_groups` 返回分组数据供前端展示。

use std::collections::HashMap;
use std::sync::LazyLock;

use serde::Serialize;

use super::actor_provider::Lane;

// ─── 分组数据结构 ───

#[derive(Debug, Clone, Serialize)]
pub struct GenreGroup {
    /// 大类别名，如「主題」「角色」「服裝」等
    pub category: String,
    /// 该类别下的分类名列表
    pub genres: Vec<String>,
}

/// 分类分组数据：有码 + 无码分开
#[derive(Debug, Clone, Serialize)]
pub struct JavbusGenreData {
    pub censored: Vec<GenreGroup>,
    pub uncensored: Vec<GenreGroup>,
}

struct GenreEntry {
    category: &'static str,
    name: &'static str,
    id: &'static str,
}

// ─── 有码分类原始数据 ───

const CENSORED_ENTRIES: &[GenreEntry] = &[
    // 主題
    GenreEntry { category: "主題", name: "折磨", id: "62" },
    GenreEntry { category: "主題", name: "嘔吐", id: "5g" },
    GenreEntry { category: "主題", name: "觸手", id: "59" },
    GenreEntry { category: "主題", name: "蠻橫嬌羞", id: "57" },
    GenreEntry { category: "主題", name: "處男", id: "52" },
    GenreEntry { category: "主題", name: "正太控", id: "4y" },
    GenreEntry { category: "主題", name: "出軌", id: "4r" },
    GenreEntry { category: "主題", name: "瘙癢", id: "4e" },
    GenreEntry { category: "主題", name: "運動", id: "4d" },
    GenreEntry { category: "主題", name: "女同接吻", id: "4a" },
    GenreEntry { category: "主題", name: "性感的", id: "49" },
    GenreEntry { category: "主題", name: "美容院", id: "44" },
    GenreEntry { category: "主題", name: "處女", id: "41" },
    GenreEntry { category: "主題", name: "爛醉如泥的", id: "40" },
    GenreEntry { category: "主題", name: "殘忍畫面", id: "3x" },
    GenreEntry { category: "主題", name: "妄想", id: "3w" },
    GenreEntry { category: "主題", name: "惡作劇", id: "3v" },
    GenreEntry { category: "主題", name: "學校作品", id: "3t" },
    GenreEntry { category: "主題", name: "粗暴", id: "3r" },
    GenreEntry { category: "主題", name: "通姦", id: "3g" },
    GenreEntry { category: "主題", name: "姐妹", id: "3e" },
    GenreEntry { category: "主題", name: "雙性人", id: "3d" },
    GenreEntry { category: "主題", name: "跳舞", id: "3c" },
    GenreEntry { category: "主題", name: "性奴", id: "3b" },
    GenreEntry { category: "主題", name: "倒追", id: "37" },
    GenreEntry { category: "主題", name: "性騷擾", id: "35" },
    GenreEntry { category: "主題", name: "其他", id: "2y" },
    GenreEntry { category: "主題", name: "戀腿癖", id: "2x" },
    GenreEntry { category: "主題", name: "偷窥", id: "2v" },
    GenreEntry { category: "主題", name: "花癡", id: "2t" },
    GenreEntry { category: "主題", name: "男同性恋", id: "2r" },
    GenreEntry { category: "主題", name: "情侶", id: "2e" },
    GenreEntry { category: "主題", name: "戀乳癖", id: "2d" },
    GenreEntry { category: "主題", name: "亂倫", id: "20" },
    GenreEntry { category: "主題", name: "其他戀物癖", id: "1y" },
    GenreEntry { category: "主題", name: "偶像藝人", id: "1u" },
    GenreEntry { category: "主題", name: "野外・露出", id: "1i" },
    GenreEntry { category: "主題", name: "獵豔", id: "1e" },
    GenreEntry { category: "主題", name: "女同性戀", id: "1d" },
    GenreEntry { category: "主題", name: "企畫", id: "11" },
    GenreEntry { category: "主題", name: "10枚組", id: "6h" },
    GenreEntry { category: "主題", name: "科幻", id: "61" },
    GenreEntry { category: "主題", name: "女優ベスト・総集編", id: "6i" },
    GenreEntry { category: "主題", name: "温泉", id: "6j" },
    GenreEntry { category: "主題", name: "M男", id: "6k" },
    GenreEntry { category: "主題", name: "原作コラボ", id: "6l" },
    GenreEntry { category: "主題", name: "16時間以上作品", id: "6n" },
    GenreEntry { category: "主題", name: "デカチン・巨根", id: "6o" },
    GenreEntry { category: "主題", name: "ファン感謝・訪問", id: "6p" },
    GenreEntry { category: "主題", name: "動画", id: "6q" },
    GenreEntry { category: "主題", name: "巨尻", id: "6r" },
    GenreEntry { category: "主題", name: "ハーレム", id: "6s" },
    GenreEntry { category: "主題", name: "日焼け", id: "6t" },
    GenreEntry { category: "主題", name: "早漏", id: "6u" },
    GenreEntry { category: "主題", name: "キス・接吻", id: "6v" },
    GenreEntry { category: "主題", name: "汗だく", id: "6w" },
    GenreEntry { category: "主題", name: "スマホ専用縦動画", id: "77" },
    GenreEntry { category: "主題", name: "Vシネマ", id: "7d" },
    GenreEntry { category: "主題", name: "Don Cipote's choice", id: "7c" },
    GenreEntry { category: "主題", name: "アニメ", id: "7f" },
    GenreEntry { category: "主題", name: "アクション", id: "7g" },
    GenreEntry { category: "主題", name: "イメージビデオ（男性）", id: "7h" },
    GenreEntry { category: "主題", name: "孕ませ", id: "7i" },
    GenreEntry { category: "主題", name: "ボーイズラブ", id: "7j" },
    GenreEntry { category: "主題", name: "ビッチ", id: "7t" },
    GenreEntry { category: "主題", name: "特典あり（AVベースボール）", id: "7u" },
    GenreEntry { category: "主題", name: "コミック雑誌", id: "7v" },
    GenreEntry { category: "主題", name: "時間停止", id: "7w" },
    // 角色
    GenreEntry { category: "角色", name: "黑幫成員", id: "5w" },
    GenreEntry { category: "角色", name: "童年朋友", id: "5k" },
    GenreEntry { category: "角色", name: "公主", id: "5i" },
    GenreEntry { category: "角色", name: "亞洲女演員", id: "5f" },
    GenreEntry { category: "角色", name: "伴侶", id: "58" },
    GenreEntry { category: "角色", name: "講師", id: "4s" },
    GenreEntry { category: "角色", name: "婆婆", id: "4l" },
    GenreEntry { category: "角色", name: "格鬥家", id: "4h" },
    GenreEntry { category: "角色", name: "女檢察官", id: "3o" },
    GenreEntry { category: "角色", name: "明星臉", id: "39" },
    GenreEntry { category: "角色", name: "女主人、女老板", id: "38" },
    GenreEntry { category: "角色", name: "模特兒", id: "34" },
    GenreEntry { category: "角色", name: "秘書", id: "32" },
    GenreEntry { category: "角色", name: "美少女", id: "30" },
    GenreEntry { category: "角色", name: "新娘、年輕妻子", id: "2z" },
    GenreEntry { category: "角色", name: "姐姐", id: "2w" },
    GenreEntry { category: "角色", name: "車掌小姐", id: "2o" },
    GenreEntry { category: "角色", name: "寡婦", id: "2f" },
    GenreEntry { category: "角色", name: "千金小姐", id: "2b" },
    GenreEntry { category: "角色", name: "白人", id: "2a" },
    GenreEntry { category: "角色", name: "已婚婦女", id: "29" },
    GenreEntry { category: "角色", name: "女醫生", id: "27" },
    GenreEntry { category: "角色", name: "各種職業", id: "26" },
    GenreEntry { category: "角色", name: "妓女", id: "23" },
    GenreEntry { category: "角色", name: "賽車女郎", id: "21" },
    GenreEntry { category: "角色", name: "女大學生", id: "1x" },
    GenreEntry { category: "角色", name: "展場女孩", id: "1v" },
    GenreEntry { category: "角色", name: "女教師", id: "1n" },
    GenreEntry { category: "角色", name: "母親", id: "1k" },
    GenreEntry { category: "角色", name: "家教", id: "1c" },
    GenreEntry { category: "角色", name: "护士", id: "17" },
    GenreEntry { category: "角色", name: "蕩婦", id: "10" },
    GenreEntry { category: "角色", name: "黑人演員", id: "z" },
    GenreEntry { category: "角色", name: "女生", id: "p" },
    GenreEntry { category: "角色", name: "女主播", id: "c" },
    GenreEntry { category: "角色", name: "高中女生", id: "b" },
    GenreEntry { category: "角色", name: "服務生", id: "7" },
    GenreEntry { category: "角色", name: "魔法少女", id: "5r" },
    GenreEntry { category: "角色", name: "學生（其他）", id: "65" },
    GenreEntry { category: "角色", name: "動畫人物", id: "64" },
    GenreEntry { category: "角色", name: "遊戲的真人版", id: "6c" },
    GenreEntry { category: "角色", name: "超級女英雄", id: "6f" },
    // 服裝
    GenreEntry { category: "服裝", name: "女戰士", id: "5h" },
    GenreEntry { category: "服裝", name: "及膝襪", id: "5c" },
    GenreEntry { category: "服裝", name: "娃娃", id: "5b" },
    GenreEntry { category: "服裝", name: "女忍者", id: "56" },
    GenreEntry { category: "服裝", name: "女裝人妖", id: "55" },
    GenreEntry { category: "服裝", name: "內衣", id: "50" },
    GenreEntry { category: "服裝", name: "猥褻穿著", id: "4z" },
    GenreEntry { category: "服裝", name: "兔女郎", id: "4p" },
    GenreEntry { category: "服裝", name: "貓耳女", id: "4n" },
    GenreEntry { category: "服裝", name: "女祭司", id: "4k" },
    GenreEntry { category: "服裝", name: "泡泡襪", id: "4i" },
    GenreEntry { category: "服裝", name: "制服", id: "3i" },
    GenreEntry { category: "服裝", name: "緊身衣", id: "3a" },
    GenreEntry { category: "服裝", name: "裸體圍裙", id: "2s" },
    GenreEntry { category: "服裝", name: "迷你裙警察", id: "2m" },
    GenreEntry { category: "服裝", name: "空中小姐", id: "2l" },
    GenreEntry { category: "服裝", name: "連褲襪", id: "28" },
    GenreEntry { category: "服裝", name: "身體意識", id: "1w" },
    GenreEntry { category: "服裝", name: "OL", id: "18" },
    GenreEntry { category: "服裝", name: "和服・喪服", id: "12" },
    GenreEntry { category: "服裝", name: "體育服", id: "y" },
    GenreEntry { category: "服裝", name: "水手服", id: "m" },
    GenreEntry { category: "服裝", name: "學校泳裝", id: "l" },
    GenreEntry { category: "服裝", name: "旗袍", id: "k" },
    GenreEntry { category: "服裝", name: "女傭", id: "j" },
    GenreEntry { category: "服裝", name: "迷你裙", id: "i" },
    GenreEntry { category: "服裝", name: "校服", id: "a" },
    GenreEntry { category: "服裝", name: "泳裝", id: "9" },
    GenreEntry { category: "服裝", name: "眼鏡", id: "8" },
    GenreEntry { category: "服裝", name: "角色扮演", id: "1" },
    GenreEntry { category: "服裝", name: "哥德蘿莉", id: "6b" },
    // 體型
    GenreEntry { category: "體型", name: "超乳", id: "5d" },
    GenreEntry { category: "體型", name: "肌肉", id: "4x" },
    GenreEntry { category: "體型", name: "乳房", id: "3n" },
    GenreEntry { category: "體型", name: "嬌小的", id: "3k" },
    GenreEntry { category: "體型", name: "屁股", id: "2k" },
    GenreEntry { category: "體型", name: "高", id: "2i" },
    GenreEntry { category: "體型", name: "變性者", id: "2g" },
    GenreEntry { category: "體型", name: "無毛", id: "22" },
    GenreEntry { category: "體型", name: "胖女人", id: "1t" },
    GenreEntry { category: "體型", name: "苗條", id: "1f" },
    GenreEntry { category: "體型", name: "孕婦", id: "15" },
    GenreEntry { category: "體型", name: "成熟的女人", id: "13" },
    GenreEntry { category: "體型", name: "蘿莉塔", id: "w" },
    GenreEntry { category: "體型", name: "貧乳・微乳", id: "t" },
    GenreEntry { category: "體型", name: "巨乳", id: "e" },
    // 行為
    GenreEntry { category: "行為", name: "顏面騎乘", id: "4w" },
    GenreEntry { category: "行為", name: "食糞", id: "4t" },
    GenreEntry { category: "行為", name: "足交", id: "4j" },
    GenreEntry { category: "行為", name: "母乳", id: "47" },
    GenreEntry { category: "行為", name: "手指插入", id: "46" },
    GenreEntry { category: "行為", name: "按摩", id: "45" },
    GenreEntry { category: "行為", name: "女上位", id: "42" },
    GenreEntry { category: "行為", name: "舔陰", id: "3q" },
    GenreEntry { category: "行為", name: "拳交", id: "3l" },
    GenreEntry { category: "行為", name: "深喉", id: "3f" },
    GenreEntry { category: "行為", name: "69", id: "2h" },
    GenreEntry { category: "行為", name: "淫語", id: "24" },
    GenreEntry { category: "行為", name: "潮吹", id: "1z" },
    GenreEntry { category: "行為", name: "乳交", id: "1s" },
    GenreEntry { category: "行為", name: "排便", id: "1r" },
    GenreEntry { category: "行為", name: "飲尿", id: "1p" },
    GenreEntry { category: "行為", name: "口交", id: "1o" },
    GenreEntry { category: "行為", name: "濫交", id: "1j" },
    GenreEntry { category: "行為", name: "放尿", id: "19" },
    GenreEntry { category: "行為", name: "打手槍", id: "x" },
    GenreEntry { category: "行為", name: "吞精", id: "u" },
    GenreEntry { category: "行為", name: "肛交", id: "r" },
    GenreEntry { category: "行為", name: "顏射", id: "n" },
    GenreEntry { category: "行為", name: "自慰", id: "h" },
    GenreEntry { category: "行為", name: "中出", id: "4" },
    GenreEntry { category: "行為", name: "肛内中出", id: "6m" },
    // 玩法
    GenreEntry { category: "玩法", name: "立即口交", id: "51" },
    GenreEntry { category: "玩法", name: "女優按摩棒", id: "4f" },
    GenreEntry { category: "玩法", name: "子宮頸", id: "4c" },
    GenreEntry { category: "玩法", name: "催眠", id: "4b" },
    GenreEntry { category: "玩法", name: "乳液", id: "3z" },
    GenreEntry { category: "玩法", name: "羞恥", id: "3y" },
    GenreEntry { category: "玩法", name: "凌辱", id: "3s" },
    GenreEntry { category: "玩法", name: "拘束", id: "3p" },
    GenreEntry { category: "玩法", name: "輪姦", id: "3m" },
    GenreEntry { category: "玩法", name: "插入異物", id: "3h" },
    GenreEntry { category: "玩法", name: "鴨嘴", id: "36" },
    GenreEntry { category: "玩法", name: "灌腸", id: "2u" },
    GenreEntry { category: "玩法", name: "監禁", id: "25" },
    GenreEntry { category: "玩法", name: "紧缚", id: "1q" },
    GenreEntry { category: "玩法", name: "強姦", id: "1m" },
    GenreEntry { category: "玩法", name: "藥物", id: "1l" },
    GenreEntry { category: "玩法", name: "汽車性愛", id: "1h" },
    GenreEntry { category: "玩法", name: "SM", id: "1b" },
    GenreEntry { category: "玩法", name: "糞便", id: "1a" },
    GenreEntry { category: "玩法", name: "玩具", id: "14" },
    GenreEntry { category: "玩法", name: "跳蛋", id: "q" },
    GenreEntry { category: "玩法", name: "緊縛", id: "d" },
    GenreEntry { category: "玩法", name: "按摩棒", id: "6" },
    GenreEntry { category: "玩法", name: "多P", id: "3" },
    GenreEntry { category: "玩法", name: "性愛", id: "5m" },
    GenreEntry { category: "玩法", name: "假陽具", id: "5y" },
    GenreEntry { category: "玩法", name: "逆強姦", id: "63" },
    // 類別
    GenreEntry { category: "類別", name: "合作作品", id: "60" },
    GenreEntry { category: "類別", name: "恐怖", id: "5z" },
    GenreEntry { category: "類別", name: "給女性觀眾", id: "5t" },
    GenreEntry { category: "類別", name: "教學", id: "5s" },
    GenreEntry { category: "類別", name: "DMM專屬", id: "5q" },
    GenreEntry { category: "類別", name: "R-15", id: "5o" },
    GenreEntry { category: "類別", name: "R-18", id: "5n" },
    GenreEntry { category: "類別", name: "3D", id: "5e" },
    GenreEntry { category: "類別", name: "特效", id: "5a" },
    GenreEntry { category: "類別", name: "故事集", id: "54" },
    GenreEntry { category: "類別", name: "限時降價", id: "53" },
    GenreEntry { category: "類別", name: "複刻版", id: "4v" },
    GenreEntry { category: "類別", name: "戲劇", id: "4u" },
    GenreEntry { category: "類別", name: "戀愛", id: "4q" },
    GenreEntry { category: "類別", name: "高畫質", id: "4o" },
    GenreEntry { category: "類別", name: "主觀視角", id: "4m" },
    GenreEntry { category: "類別", name: "介紹影片", id: "48" },
    GenreEntry { category: "類別", name: "4小時以上作品", id: "43" },
    GenreEntry { category: "類別", name: "薄馬賽克", id: "3u" },
    GenreEntry { category: "類別", name: "經典", id: "3j" },
    GenreEntry { category: "類別", name: "首次亮相", id: "33" },
    GenreEntry { category: "類別", name: "數位馬賽克", id: "31" },
    GenreEntry { category: "類別", name: "投稿", id: "2p" },
    GenreEntry { category: "類別", name: "纪录片", id: "2n" },
    GenreEntry { category: "類別", name: "國外進口", id: "2c" },
    GenreEntry { category: "類別", name: "第一人稱攝影", id: "1g" },
    GenreEntry { category: "類別", name: "業餘", id: "16" },
    GenreEntry { category: "類別", name: "局部特寫", id: "s" },
    GenreEntry { category: "類別", name: "獨立製作", id: "o" },
    GenreEntry { category: "類別", name: "DMM獨家", id: "g" },
    GenreEntry { category: "類別", name: "單體作品", id: "f" },
    GenreEntry { category: "類別", name: "合集", id: "2" },
    GenreEntry { category: "類別", name: "高清", id: "hd" },
    GenreEntry { category: "類別", name: "字幕", id: "sub" },
    GenreEntry { category: "類別", name: "天堂TV", id: "2j" },
    GenreEntry { category: "類別", name: "DVD多士爐", id: "4g" },
    GenreEntry { category: "類別", name: "AV OPEN 2014 スーパーヘビー", id: "66" },
    GenreEntry { category: "類別", name: "AV OPEN 2014 ヘビー級", id: "69" },
    GenreEntry { category: "類別", name: "AV OPEN 2014 ミドル級", id: "6a" },
    GenreEntry { category: "類別", name: "AV OPEN 2015 マニア/フェチ部門", id: "70" },
    GenreEntry { category: "類別", name: "AV OPEN 2015 熟女部門", id: "71" },
    GenreEntry { category: "類別", name: "AV OPEN 2015 企画部門", id: "72" },
    GenreEntry { category: "類別", name: "AV OPEN 2015 乙女部門", id: "73" },
    GenreEntry { category: "類別", name: "AV OPEN 2015 素人部門", id: "74" },
    GenreEntry { category: "類別", name: "AV OPEN 2015 SM/ハード部門", id: "75" },
    GenreEntry { category: "類別", name: "AV OPEN 2015 女優部門", id: "76" },
    GenreEntry { category: "類別", name: "AVOPEN2016人妻・熟女部門", id: "7k" },
    GenreEntry { category: "類別", name: "AVOPEN2016企画部門", id: "7l" },
    GenreEntry { category: "類別", name: "AVOPEN2016ハード部門", id: "7m" },
    GenreEntry { category: "類別", name: "AVOPEN2016マニア・フェチ部門", id: "7n" },
    GenreEntry { category: "類別", name: "AVOPEN2016乙女部門", id: "7o" },
    GenreEntry { category: "類別", name: "AVOPEN2016女優部門", id: "7p" },
    GenreEntry { category: "類別", name: "AVOPEN2016ドラマ・ドキュメンタリー部門", id: "7q" },
    GenreEntry { category: "類別", name: "AVOPEN2016素人部門", id: "7r" },
    GenreEntry { category: "類別", name: "AVOPEN2016バラエティ部門", id: "7s" },
    GenreEntry { category: "類別", name: "VR専用", id: "7x" },
    GenreEntry { category: "類別", name: "堵嘴·喜劇", id: "7y" },
    GenreEntry { category: "類別", name: "幻想", id: "7z" },
    GenreEntry { category: "類別", name: "性別轉型·女性化", id: "80" },
    GenreEntry { category: "類別", name: "為智能手機推薦垂直視頻", id: "81" },
    GenreEntry { category: "類別", name: "設置項目", id: "82" },
    GenreEntry { category: "類別", name: "迷你係列", id: "83" },
    GenreEntry { category: "類別", name: "體驗懺悔", id: "84" },
    GenreEntry { category: "類別", name: "黑暗系統", id: "85" },
    // 其他
    GenreEntry { category: "其他", name: "オナサポ", id: "dx" },
    GenreEntry { category: "其他", name: "アスリート", id: "dy" },
    GenreEntry { category: "其他", name: "覆面・マスク", id: "dz" },
    GenreEntry { category: "其他", name: "ハイクオリティVR", id: "e0" },
    GenreEntry { category: "其他", name: "ヘルス・ソープ", id: "e1" },
    GenreEntry { category: "其他", name: "ホテル", id: "e2" },
    GenreEntry { category: "其他", name: "アクメ・オーガズム", id: "e3" },
    GenreEntry { category: "其他", name: "花嫁", id: "e4" },
    GenreEntry { category: "其他", name: "デート", id: "e5" },
    GenreEntry { category: "其他", name: "軟体", id: "e6" },
    GenreEntry { category: "其他", name: "娘・養女", id: "e7" },
    GenreEntry { category: "其他", name: "スパンキング", id: "e8" },
    GenreEntry { category: "其他", name: "スワッピング・夫婦交換", id: "e9" },
    GenreEntry { category: "其他", name: "部下・同僚", id: "ea" },
    GenreEntry { category: "其他", name: "旅行", id: "eb" },
    GenreEntry { category: "其他", name: "胸チラ", id: "ec" },
    GenreEntry { category: "其他", name: "バック", id: "ed" },
    GenreEntry { category: "其他", name: "エロス", id: "ee" },
    GenreEntry { category: "其他", name: "男の潮吹き", id: "ef" },
    GenreEntry { category: "其他", name: "女上司", id: "eg" },
    GenreEntry { category: "其他", name: "セクシー", id: "eh" },
    GenreEntry { category: "其他", name: "受付嬢", id: "ei" },
    GenreEntry { category: "其他", name: "ノーブラ", id: "ej" },
    GenreEntry { category: "其他", name: "白目・失神", id: "ek" },
    GenreEntry { category: "其他", name: "M女", id: "el" },
    GenreEntry { category: "其他", name: "女王様", id: "em" },
    GenreEntry { category: "其他", name: "ノーパン", id: "en" },
    GenreEntry { category: "其他", name: "セレブ", id: "eo" },
    GenreEntry { category: "其他", name: "病院・クリニック", id: "ep" },
    GenreEntry { category: "其他", name: "面接", id: "eq" },
    GenreEntry { category: "其他", name: "お風呂", id: "er" },
    GenreEntry { category: "其他", name: "叔母さん", id: "es" },
    GenreEntry { category: "其他", name: "罵倒", id: "et" },
    GenreEntry { category: "其他", name: "お爺ちゃん", id: "eu" },
    GenreEntry { category: "其他", name: "逆レイプ", id: "ev" },
    GenreEntry { category: "其他", name: "ディルド", id: "ew" },
    GenreEntry { category: "其他", name: "ヨガ", id: "ex" },
    GenreEntry { category: "其他", name: "飲み会・合コン", id: "ey" },
    GenreEntry { category: "其他", name: "部活・マネージャー", id: "ez" },
    GenreEntry { category: "其他", name: "お婆ちゃん", id: "f0" },
    GenreEntry { category: "其他", name: "ビジネススーツ", id: "f1" },
    GenreEntry { category: "其他", name: "チアガール", id: "f2" },
    GenreEntry { category: "其他", name: "ママ友", id: "f3" },
    GenreEntry { category: "其他", name: "エマニエル", id: "f4" },
    GenreEntry { category: "其他", name: "妄想族", id: "f5" },
    GenreEntry { category: "其他", name: "蝋燭", id: "f6" },
    GenreEntry { category: "其他", name: "鼻フック", id: "f7" },
    GenreEntry { category: "其他", name: "放置", id: "f8" },
    GenreEntry { category: "其他", name: "サンプル動画", id: "f9" },
    GenreEntry { category: "其他", name: "サイコ・スリラー", id: "fa" },
    GenreEntry { category: "其他", name: "ラブコメ", id: "fb" },
    GenreEntry { category: "其他", name: "オタク", id: "fc" },
    GenreEntry { category: "其他", name: "4K", id: "fd" },
    GenreEntry { category: "其他", name: "福袋", id: "fe" },
    GenreEntry { category: "其他", name: "玩具責め", id: "ff" },
    GenreEntry { category: "其他", name: "女優", id: "fj" },
    GenreEntry { category: "其他", name: "お掃除フェラ", id: "fl" },
    GenreEntry { category: "其他", name: "筆おろし", id: "fn" },
    GenreEntry { category: "其他", name: "美脚", id: "fq" },
    GenreEntry { category: "其他", name: "美尻", id: "ft" },
    GenreEntry { category: "其他", name: "フェチ", id: "fu" },
    GenreEntry { category: "其他", name: "羞恥プレイ", id: "fw" },
    GenreEntry { category: "其他", name: "逆ナンパ", id: "fx" },
    GenreEntry { category: "其他", name: "着衣", id: "fy" },
    GenreEntry { category: "其他", name: "誘惑", id: "g0" },
    GenreEntry { category: "其他", name: "チラリズム", id: "g1" },
    GenreEntry { category: "其他", name: "写真集", id: "g2" },
    GenreEntry { category: "其他", name: "書籍版", id: "g3" },
    GenreEntry { category: "其他", name: "SM拘束", id: "g4" },
    GenreEntry { category: "其他", name: "ドキュメント", id: "g6" },
    GenreEntry { category: "其他", name: "グッズ", id: "g9" },
    GenreEntry { category: "其他", name: "Tシャツ", id: "ga" },
    GenreEntry { category: "其他", name: "失禁", id: "gb" },
    GenreEntry { category: "其他", name: "オナホール", id: "gc" },
    GenreEntry { category: "其他", name: "カップホール", id: "gd" },
    GenreEntry { category: "其他", name: "非貫通", id: "ge" },
    GenreEntry { category: "其他", name: "ローション付き", id: "gf" },
    GenreEntry { category: "其他", name: "配信専用", id: "gh" },
    GenreEntry { category: "其他", name: "官能小説", id: "gi" },
    GenreEntry { category: "其他", name: "CD", id: "gj" },
    GenreEntry { category: "其他", name: "生挿入", id: "gk" },
    GenreEntry { category: "其他", name: "風俗", id: "gl" },
    GenreEntry { category: "其他", name: "外国人", id: "gm" },
    GenreEntry { category: "其他", name: "淫語責め", id: "gn" },
    GenreEntry { category: "其他", name: "アナルファック", id: "go" },
    GenreEntry { category: "其他", name: "脚コキ", id: "gp" },
    GenreEntry { category: "其他", name: "オイルプレイ", id: "gq" },
    GenreEntry { category: "其他", name: "キャバ嬢", id: "gr" },
    GenreEntry { category: "其他", name: "調教", id: "gs" },
    GenreEntry { category: "其他", name: "ローション・オイル", id: "gt" },
    GenreEntry { category: "其他", name: "媚薬", id: "gu" },
    GenreEntry { category: "其他", name: "顔面騎乗位", id: "gv" },
    GenreEntry { category: "其他", name: "微乳", id: "gw" },
    GenreEntry { category: "其他", name: "デカチン", id: "gx" },
    GenreEntry { category: "其他", name: "3P、4P", id: "gy" },
    GenreEntry { category: "其他", name: "野外", id: "gz" },
    GenreEntry { category: "其他", name: "露出", id: "h0" },
    GenreEntry { category: "其他", name: "レイプ", id: "h1" },
    GenreEntry { category: "其他", name: "ベスト、総集編", id: "h2" },
    GenreEntry { category: "其他", name: "マジックミラー号", id: "h3" },
    GenreEntry { category: "其他", name: "看護師", id: "h4" },
    GenreEntry { category: "其他", name: "アイドル", id: "h5" },
    GenreEntry { category: "其他", name: "妹", id: "h6" },
    GenreEntry { category: "其他", name: "スクール水着", id: "h7" },
    GenreEntry { category: "其他", name: "デリヘル", id: "h8" },
    GenreEntry { category: "其他", name: "童貞モノ", id: "ha" },
    GenreEntry { category: "其他", name: "ブルマ", id: "hb" },
    GenreEntry { category: "其他", name: "ホテヘル", id: "hc" },
    GenreEntry { category: "其他", name: "ロリータ", id: "he" },
    GenreEntry { category: "其他", name: "ミニスカート", id: "hf" },
    GenreEntry { category: "其他", name: "尻", id: "hg" },
    GenreEntry { category: "其他", name: "奴隷", id: "hh" },
    GenreEntry { category: "其他", name: "芸能人", id: "hi" },
    GenreEntry { category: "其他", name: "下着", id: "hj" },
    GenreEntry { category: "其他", name: "母親", id: "hk" },
    GenreEntry { category: "其他", name: "湯", id: "hl" },
    GenreEntry { category: "其他", name: "教師", id: "hm" },
    GenreEntry { category: "其他", name: "ストッキング", id: "hn" },
    GenreEntry { category: "其他", name: "電車、バス", id: "ho" },
    GenreEntry { category: "其他", name: "健康診断", id: "hp" },
    GenreEntry { category: "其他", name: "野球拳", id: "hq" },
    GenreEntry { category: "其他", name: "浴衣", id: "hr" },
    GenreEntry { category: "其他", name: "爆乳", id: "hs" },
    GenreEntry { category: "其他", name: "ソープ", id: "ht" },
    GenreEntry { category: "其他", name: "スワッピング", id: "hu" },
    GenreEntry { category: "其他", name: "メガネ", id: "hv" },
    GenreEntry { category: "其他", name: "素股", id: "hw" },
    GenreEntry { category: "其他", name: "ドリンク", id: "hx" },
    GenreEntry { category: "其他", name: "フルハイビジョン(FHD)", id: "hy" },
    GenreEntry { category: "其他", name: "三十路", id: "hz" },
    GenreEntry { category: "其他", name: "羞恥・辱め", id: "i0" },
    GenreEntry { category: "其他", name: "パンチラモノ", id: "i1" },
    GenreEntry { category: "其他", name: "放尿・失禁", id: "i2" },
    GenreEntry { category: "其他", name: "五十路", id: "i3" },
    GenreEntry { category: "其他", name: "ショートヘアー", id: "i4" },
    GenreEntry { category: "其他", name: "着物・浴衣", id: "i5" },
    GenreEntry { category: "其他", name: "清楚", id: "i6" },
    GenreEntry { category: "其他", name: "四十路", id: "i7" },
    GenreEntry { category: "其他", name: "VR", id: "i8" },
    GenreEntry { category: "其他", name: "オモチャ", id: "i9" },
    GenreEntry { category: "其他", name: "エステ・マッサージ", id: "ia" },
    GenreEntry { category: "其他", name: "Gカップ", id: "ib" },
    GenreEntry { category: "其他", name: "目隠し", id: "ic" },
    GenreEntry { category: "其他", name: "ドラッグ・媚薬", id: "id" },
    GenreEntry { category: "其他", name: "六十路", id: "ie" },
    GenreEntry { category: "其他", name: "淫語モノ", id: "if" },
    GenreEntry { category: "其他", name: "口内発射", id: "ig" },
    GenreEntry { category: "其他", name: "童顔", id: "ih" },
    GenreEntry { category: "其他", name: "スチュワーデス・CA", id: "ii" },
    GenreEntry { category: "其他", name: "Dカップ", id: "ij" },
    GenreEntry { category: "其他", name: "美熟女", id: "ik" },
    GenreEntry { category: "其他", name: "MGSだけのおまけ映像付き", id: "il" },
    GenreEntry { category: "其他", name: "手マン", id: "im" },
    GenreEntry { category: "其他", name: "パンストモノ", id: "in" },
    GenreEntry { category: "其他", name: "フェラモノ", id: "io" },
    GenreEntry { category: "其他", name: "性教育", id: "ip" },
    GenreEntry { category: "其他", name: "HowTo", id: "iq" },
    GenreEntry { category: "其他", name: "MGS限定特典映像", id: "ir" },
    GenreEntry { category: "其他", name: "寝取り･寝取られ", id: "is" },
    GenreEntry { category: "其他", name: "Eカップ", id: "it" },
    GenreEntry { category: "其他", name: "Fカップ", id: "iu" },
    GenreEntry { category: "其他", name: "ロングヘアー", id: "iv" },
    GenreEntry { category: "其他", name: "黒髪", id: "iw" },
    GenreEntry { category: "其他", name: "ショートヘア", id: "ix" },
    GenreEntry { category: "其他", name: "金髪", id: "iy" },
    GenreEntry { category: "其他", name: "茶髪", id: "iz" },
    GenreEntry { category: "其他", name: "女子高生", id: "j0" },
    GenreEntry { category: "其他", name: "ハーフ", id: "j1" },
    GenreEntry { category: "其他", name: "金髪・ブロンド", id: "j2" },
    GenreEntry { category: "其他", name: "初撮り", id: "j3" },
    GenreEntry { category: "其他", name: "介護", id: "j4" },
    GenreEntry { category: "其他", name: "Hカップ", id: "j5" },
    GenreEntry { category: "其他", name: "期間限定販売", id: "j6" },
    GenreEntry { category: "其他", name: "多人数", id: "j7" },
    GenreEntry { category: "其他", name: "風俗嬢", id: "j8" },
    GenreEntry { category: "其他", name: "PICKUP素人", id: "j9" },
    GenreEntry { category: "其他", name: "オイル・ローション", id: "ja" },
    GenreEntry { category: "其他", name: "8KVR", id: "jb" },
    GenreEntry { category: "其他", name: "プレステージ20周年特別企画", id: "jc" },
    GenreEntry { category: "其他", name: "口内射精", id: "jd" },
    GenreEntry { category: "其他", name: "美女", id: "je" },
    GenreEntry { category: "其他", name: "MGSだけの特典映像付", id: "jf" },
    GenreEntry { category: "其他", name: "色白", id: "jg" },
    GenreEntry { category: "其他", name: "総集編・ベスト", id: "jh" },
    GenreEntry { category: "其他", name: "近●相●", id: "ji" },
    GenreEntry { category: "其他", name: "ハイビジョン(HD)", id: "jj" },
    GenreEntry { category: "其他", name: "配信専用素人", id: "jk" },
    GenreEntry { category: "其他", name: "台湾モデル", id: "jl" },
    GenreEntry { category: "其他", name: "ショートカット", id: "jm" },
    GenreEntry { category: "其他", name: "巨乳", id: "jn" },
    GenreEntry { category: "其他", name: "お姉さん", id: "jp" },
    GenreEntry { category: "其他", name: "長身", id: "jq" },
    GenreEntry { category: "其他", name: "ギャル", id: "jr" },
    GenreEntry { category: "其他", name: "美乳", id: "js" },
    GenreEntry { category: "其他", name: "パイパン", id: "jt" },
    GenreEntry { category: "其他", name: "スレンダー", id: "ju" },
    GenreEntry { category: "其他", name: "貧乳・微乳", id: "jv" },
    GenreEntry { category: "其他", name: "ミニ系", id: "jw" },
    GenreEntry { category: "其他", name: "小柄", id: "jx" },
    GenreEntry { category: "其他", name: "くびれ", id: "jy" },
    GenreEntry { category: "其他", name: "ぽっちゃり", id: "jz" },
    GenreEntry { category: "其他", name: "黒髪", id: "k0" },
    GenreEntry { category: "其他", name: "色白", id: "k1" },
    GenreEntry { category: "其他", name: "金髪", id: "k2" },
    GenreEntry { category: "其他", name: "茶髪", id: "k3" },
    GenreEntry { category: "其他", name: "美脚", id: "k4" },
    GenreEntry { category: "其他", name: "ロングヘアー", id: "k5" },
    GenreEntry { category: "其他", name: "外国人", id: "k6" },
    GenreEntry { category: "其他", name: "ショートヘアー", id: "k7" },
    GenreEntry { category: "其他", name: "お嬢様・令嬢", id: "k8" },
    GenreEntry { category: "其他", name: "ミディアムヘアー", id: "k9" },
    GenreEntry { category: "其他", name: "AI生成作品", id: "ka" },
    GenreEntry { category: "其他", name: "個人撮影", id: "kb" },
    GenreEntry { category: "其他", name: "アナルセックス（男の娘）", id: "kc" },
];

// ─── 无码分类原始数据 ───

const UNCENSORED_ENTRIES: &[GenreEntry] = &[
    // 主題
    GenreEntry { category: "主題", name: "高清", id: "hd" },
    GenreEntry { category: "主題", name: "字幕", id: "sub" },
    GenreEntry { category: "主題", name: "推薦作品", id: "1bc" },
    GenreEntry { category: "主題", name: "通姦", id: "yz" },
    GenreEntry { category: "主題", name: "淋浴", id: "3q" },
    GenreEntry { category: "主題", name: "舌頭", id: "8q" },
    GenreEntry { category: "主題", name: "下流", id: "ap" },
    GenreEntry { category: "主題", name: "敏感", id: "8y" },
    GenreEntry { category: "主題", name: "變態", id: "29" },
    GenreEntry { category: "主題", name: "願望", id: "8w" },
    GenreEntry { category: "主題", name: "慾求不滿", id: "au" },
    GenreEntry { category: "主題", name: "服侍", id: "nc" },
    GenreEntry { category: "主題", name: "外遇", id: "ee" },
    GenreEntry { category: "主題", name: "訪問", id: "19o" },
    GenreEntry { category: "主題", name: "性伴侶", id: "7z" },
    GenreEntry { category: "主題", name: "保守", id: "bk" },
    GenreEntry { category: "主題", name: "購物", id: "17g" },
    GenreEntry { category: "主題", name: "誘惑", id: "6p" },
    GenreEntry { category: "主題", name: "出差", id: "eu" },
    GenreEntry { category: "主題", name: "煩惱", id: "xx" },
    GenreEntry { category: "主題", name: "主動", id: "jm" },
    GenreEntry { category: "主題", name: "再會", id: "vr" },
    GenreEntry { category: "主題", name: "戀物癖", id: "bd" },
    GenreEntry { category: "主題", name: "問題", id: "vn" },
    GenreEntry { category: "主題", name: "騙奸", id: "164" },
    GenreEntry { category: "主題", name: "鬼混", id: "ui" },
    GenreEntry { category: "主題", name: "高手", id: "u4" },
    GenreEntry { category: "主題", name: "順從", id: "1cu" },
    GenreEntry { category: "主題", name: "密會", id: "v6" },
    GenreEntry { category: "主題", name: "做家務", id: "sb" },
    GenreEntry { category: "主題", name: "秘密", id: "y2" },
    GenreEntry { category: "主題", name: "送貨上門", id: "pm" },
    GenreEntry { category: "主題", name: "壓力", id: "e5" },
    GenreEntry { category: "主題", name: "處女作", id: "t9" },
    GenreEntry { category: "主題", name: "淫語", id: "1cw" },
    GenreEntry { category: "主題", name: "問卷", id: "gc" },
    GenreEntry { category: "主題", name: "住一宿", id: "wd" },
    GenreEntry { category: "主題", name: "眼淚", id: "12d" },
    GenreEntry { category: "主題", name: "跪求", id: "7d" },
    GenreEntry { category: "主題", name: "求職", id: "7g" },
    GenreEntry { category: "主題", name: "婚禮", id: "8i" },
    GenreEntry { category: "主題", name: "第一視角", id: "gre001" },
    GenreEntry { category: "主題", name: "洗澡", id: "gre002" },
    GenreEntry { category: "主題", name: "首次", id: "gre003" },
    GenreEntry { category: "主題", name: "劇情", id: "gre004" },
    GenreEntry { category: "主題", name: "約會", id: "gre005" },
    GenreEntry { category: "主題", name: "實拍", id: "gre006" },
    GenreEntry { category: "主題", name: "同性戀", id: "gre007" },
    GenreEntry { category: "主題", name: "幻想", id: "gre008" },
    GenreEntry { category: "主題", name: "淫蕩", id: "gre009" },
    GenreEntry { category: "主題", name: "旅行", id: "gre010" },
    GenreEntry { category: "主題", name: "面試", id: "gre011" },
    GenreEntry { category: "主題", name: "喝酒", id: "gre012" },
    GenreEntry { category: "主題", name: "尖叫", id: "gre013" },
    GenreEntry { category: "主題", name: "新年", id: "gre014" },
    GenreEntry { category: "主題", name: "借款", id: "gre015" },
    GenreEntry { category: "主題", name: "不忠", id: "gre016" },
    GenreEntry { category: "主題", name: "檢查", id: "gre017" },
    GenreEntry { category: "主題", name: "羞恥", id: "gre018" },
    GenreEntry { category: "主題", name: "勾引", id: "gre019" },
    GenreEntry { category: "主題", name: "新人", id: "gre020" },
    GenreEntry { category: "主題", name: "推銷", id: "gre021" },
    GenreEntry { category: "主題", name: "ブルマ", id: "gre153" },
    // 角色
    GenreEntry { category: "角色", name: "AV女優", id: "c" },
    GenreEntry { category: "角色", name: "情人", id: "2r" },
    GenreEntry { category: "角色", name: "丈夫", id: "yg" },
    GenreEntry { category: "角色", name: "辣妹", id: "3" },
    GenreEntry { category: "角色", name: "S級女優", id: "1av" },
    GenreEntry { category: "角色", name: "白領", id: "18" },
    GenreEntry { category: "角色", name: "偶像", id: "1y" },
    GenreEntry { category: "角色", name: "兒子", id: "wc" },
    GenreEntry { category: "角色", name: "女僕", id: "13" },
    GenreEntry { category: "角色", name: "老師", id: "jk" },
    GenreEntry { category: "角色", name: "夫婦", id: "bm" },
    GenreEntry { category: "角色", name: "保健室", id: "r5" },
    GenreEntry { category: "角色", name: "朋友", id: "18t" },
    GenreEntry { category: "角色", name: "工作人員", id: "mr" },
    GenreEntry { category: "角色", name: "明星", id: "o4" },
    GenreEntry { category: "角色", name: "同事", id: "m8" },
    GenreEntry { category: "角色", name: "面具男", id: "11x" },
    GenreEntry { category: "角色", name: "上司", id: "43" },
    GenreEntry { category: "角色", name: "睡眠系", id: "165" },
    GenreEntry { category: "角色", name: "奶奶", id: "1a1" },
    GenreEntry { category: "角色", name: "播音員", id: "12r" },
    GenreEntry { category: "角色", name: "鄰居", id: "pk" },
    GenreEntry { category: "角色", name: "親人", id: "1co" },
    GenreEntry { category: "角色", name: "店員", id: "48" },
    GenreEntry { category: "角色", name: "魔女", id: "9a" },
    GenreEntry { category: "角色", name: "視訊小姐", id: "3r" },
    GenreEntry { category: "角色", name: "大學生", id: "5d" },
    GenreEntry { category: "角色", name: "寡婦", id: "ok" },
    GenreEntry { category: "角色", name: "小姐", id: "ad" },
    GenreEntry { category: "角色", name: "秘書", id: "ct" },
    GenreEntry { category: "角色", name: "人妖", id: "2e" },
    GenreEntry { category: "角色", name: "啦啦隊", id: "1d3" },
    GenreEntry { category: "角色", name: "美容師", id: "8d" },
    GenreEntry { category: "角色", name: "岳母", id: "sv" },
    GenreEntry { category: "角色", name: "警察", id: "1bx" },
    GenreEntry { category: "角色", name: "熟女", id: "gre022" },
    GenreEntry { category: "角色", name: "素人", id: "gre023" },
    GenreEntry { category: "角色", name: "人妻", id: "gre024" },
    GenreEntry { category: "角色", name: "痴女", id: "gre025" },
    GenreEntry { category: "角色", name: "角色扮演", id: "gre026" },
    GenreEntry { category: "角色", name: "蘿莉", id: "gre027" },
    GenreEntry { category: "角色", name: "姐姐", id: "gre028" },
    GenreEntry { category: "角色", name: "模特", id: "gre029" },
    GenreEntry { category: "角色", name: "教師", id: "gre030" },
    GenreEntry { category: "角色", name: "學生", id: "gre031" },
    GenreEntry { category: "角色", name: "少女", id: "gre032" },
    GenreEntry { category: "角色", name: "新手", id: "gre033" },
    GenreEntry { category: "角色", name: "男友", id: "gre034" },
    GenreEntry { category: "角色", name: "護士", id: "gre035" },
    GenreEntry { category: "角色", name: "媽媽", id: "gre036" },
    GenreEntry { category: "角色", name: "主婦", id: "gre037" },
    GenreEntry { category: "角色", name: "孕婦", id: "gre038" },
    GenreEntry { category: "角色", name: "女教師", id: "gre039" },
    GenreEntry { category: "角色", name: "年輕人妻", id: "gre040" },
    GenreEntry { category: "角色", name: "職員", id: "gre041" },
    GenreEntry { category: "角色", name: "看護", id: "gre042" },
    GenreEntry { category: "角色", name: "外觀相似", id: "gre043" },
    GenreEntry { category: "角色", name: "色狼", id: "gre044" },
    GenreEntry { category: "角色", name: "醫生", id: "gre045" },
    GenreEntry { category: "角色", name: "新婚", id: "gre046" },
    GenreEntry { category: "角色", name: "黑人", id: "gre047" },
    GenreEntry { category: "角色", name: "空中小姐", id: "gre048" },
    GenreEntry { category: "角色", name: "運動系", id: "gre155" },
    GenreEntry { category: "角色", name: "女王", id: "gre158" },
    GenreEntry { category: "角色", name: "西裝", id: "gre159" },
    GenreEntry { category: "角色", name: "旗袍", id: "gre160" },
    GenreEntry { category: "角色", name: "兔女郎", id: "gre161" },
    GenreEntry { category: "角色", name: "白人", id: "gre163" },
    // 服裝
    GenreEntry { category: "服裝", name: "制服", id: "2" },
    GenreEntry { category: "服裝", name: "內衣", id: "5x" },
    GenreEntry { category: "服裝", name: "休閒裝", id: "19t" },
    GenreEntry { category: "服裝", name: "水手服", id: "gv" },
    GenreEntry { category: "服裝", name: "全裸", id: "mx" },
    GenreEntry { category: "服裝", name: "不穿內褲", id: "cd" },
    GenreEntry { category: "服裝", name: "和服", id: "3i" },
    GenreEntry { category: "服裝", name: "不戴胸罩", id: "ce" },
    GenreEntry { category: "服裝", name: "連衣裙", id: "16w" },
    GenreEntry { category: "服裝", name: "打底褲", id: "17y" },
    GenreEntry { category: "服裝", name: "緊身衣", id: "jg" },
    GenreEntry { category: "服裝", name: "客人", id: "qm" },
    GenreEntry { category: "服裝", name: "晚禮服", id: "f8" },
    GenreEntry { category: "服裝", name: "治癒系", id: "ab" },
    GenreEntry { category: "服裝", name: "大衣", id: "88" },
    GenreEntry { category: "服裝", name: "裸體襪子", id: "1di" },
    GenreEntry { category: "服裝", name: "絲帶", id: "wz" },
    GenreEntry { category: "服裝", name: "睡衣", id: "14" },
    GenreEntry { category: "服裝", name: "面具", id: "f7" },
    GenreEntry { category: "服裝", name: "牛仔褲", id: "17h" },
    GenreEntry { category: "服裝", name: "喪服", id: "du" },
    GenreEntry { category: "服裝", name: "極小比基尼", id: "hm" },
    GenreEntry { category: "服裝", name: "混血", id: "1dp" },
    GenreEntry { category: "服裝", name: "毛衣", id: "vx" },
    GenreEntry { category: "服裝", name: "頸鏈", id: "1bu" },
    GenreEntry { category: "服裝", name: "短褲", id: "17i" },
    GenreEntry { category: "服裝", name: "美人", id: "gre049" },
    GenreEntry { category: "服裝", name: "連褲襪", id: "gre050" },
    GenreEntry { category: "服裝", name: "裙子", id: "gre051" },
    GenreEntry { category: "服裝", name: "浴衣和服", id: "gre052" },
    GenreEntry { category: "服裝", name: "泳衣", id: "gre053" },
    GenreEntry { category: "服裝", name: "網襪", id: "gre054" },
    GenreEntry { category: "服裝", name: "眼罩", id: "gre055" },
    GenreEntry { category: "服裝", name: "圍裙", id: "gre056" },
    GenreEntry { category: "服裝", name: "比基尼", id: "gre057" },
    GenreEntry { category: "服裝", name: "情趣內衣", id: "gre058" },
    GenreEntry { category: "服裝", name: "迷你裙", id: "gre059" },
    GenreEntry { category: "服裝", name: "套裝", id: "gre060" },
    GenreEntry { category: "服裝", name: "眼鏡", id: "gre061" },
    GenreEntry { category: "服裝", name: "丁字褲", id: "gre062" },
    GenreEntry { category: "服裝", name: "陽具腰帶", id: "gre063" },
    GenreEntry { category: "服裝", name: "男装", id: "gre156" },
    GenreEntry { category: "服裝", name: "襪", id: "gre157" },
    // 體型
    GenreEntry { category: "體型", name: "美肌", id: "1da" },
    GenreEntry { category: "體型", name: "屁股", id: "zc" },
    GenreEntry { category: "體型", name: "美穴", id: "bl" },
    GenreEntry { category: "體型", name: "黑髮", id: "5g" },
    GenreEntry { category: "體型", name: "嬌小", id: "66" },
    GenreEntry { category: "體型", name: "曬痕", id: "wy" },
    GenreEntry { category: "體型", name: "F罩杯", id: "5h" },
    GenreEntry { category: "體型", name: "E罩杯", id: "3z" },
    GenreEntry { category: "體型", name: "D罩杯", id: "9x" },
    GenreEntry { category: "體型", name: "素顏", id: "4s" },
    GenreEntry { category: "體型", name: "貓眼", id: "1dd" },
    GenreEntry { category: "體型", name: "捲髮", id: "1b4" },
    GenreEntry { category: "體型", name: "虎牙", id: "17s" },
    GenreEntry { category: "體型", name: "C罩杯", id: "199" },
    GenreEntry { category: "體型", name: "I罩杯", id: "mu" },
    GenreEntry { category: "體型", name: "小麥色", id: "gz" },
    GenreEntry { category: "體型", name: "大陰蒂", id: "i0" },
    GenreEntry { category: "體型", name: "美乳", id: "gre064" },
    GenreEntry { category: "體型", name: "巨乳", id: "gre065" },
    GenreEntry { category: "體型", name: "豐滿", id: "gre066" },
    GenreEntry { category: "體型", name: "苗條", id: "gre067" },
    GenreEntry { category: "體型", name: "美臀", id: "gre068" },
    GenreEntry { category: "體型", name: "美腿", id: "gre069" },
    GenreEntry { category: "體型", name: "無毛", id: "gre070" },
    GenreEntry { category: "體型", name: "美白", id: "gre071" },
    GenreEntry { category: "體型", name: "微乳", id: "gre072" },
    GenreEntry { category: "體型", name: "性感", id: "gre073" },
    GenreEntry { category: "體型", name: "高個子", id: "gre074" },
    GenreEntry { category: "體型", name: "爆乳", id: "gre075" },
    GenreEntry { category: "體型", name: "G罩杯", id: "gre076" },
    GenreEntry { category: "體型", name: "多毛", id: "gre077" },
    GenreEntry { category: "體型", name: "巨臀", id: "gre078" },
    GenreEntry { category: "體型", name: "軟體", id: "gre079" },
    GenreEntry { category: "體型", name: "巨大陽具", id: "gre080" },
    GenreEntry { category: "體型", name: "長發", id: "gre081" },
    GenreEntry { category: "體型", name: "H罩杯", id: "gre082" },
    // 行為
    GenreEntry { category: "行為", name: "舔陰", id: "i" },
    GenreEntry { category: "行為", name: "電動陽具", id: "34" },
    GenreEntry { category: "行為", name: "淫亂", id: "3x" },
    GenreEntry { category: "行為", name: "射在外陰", id: "11a" },
    GenreEntry { category: "行為", name: "猛烈", id: "c2" },
    GenreEntry { category: "行為", name: "後入內射", id: "v4" },
    GenreEntry { category: "行為", name: "足交", id: "5u" },
    GenreEntry { category: "行為", name: "射在胸部", id: "11e" },
    GenreEntry { category: "行為", name: "側位內射", id: "uc" },
    GenreEntry { category: "行為", name: "射在腹部", id: "14w" },
    GenreEntry { category: "行為", name: "騎乘內射", id: "141" },
    GenreEntry { category: "行為", name: "射在頭髮", id: "110" },
    GenreEntry { category: "行為", name: "母乳", id: "kp" },
    GenreEntry { category: "行為", name: "站立姿勢", id: "tc" },
    GenreEntry { category: "行為", name: "肛射", id: "kv" },
    GenreEntry { category: "行為", name: "陰道擴張", id: "10p" },
    GenreEntry { category: "行為", name: "內射觀察", id: "12p" },
    GenreEntry { category: "行為", name: "射在大腿", id: "124" },
    GenreEntry { category: "行為", name: "精液流出", id: "11p" },
    GenreEntry { category: "行為", name: "射在屁股", id: "13a" },
    GenreEntry { category: "行為", name: "內射潮吹", id: "134" },
    GenreEntry { category: "行為", name: "首次肛交", id: "12x" },
    GenreEntry { category: "行為", name: "射在衣服上", id: "128" },
    GenreEntry { category: "行為", name: "首次內射", id: "14d" },
    GenreEntry { category: "行為", name: "早洩", id: "2c" },
    GenreEntry { category: "行為", name: "翻白眼", id: "12l" },
    GenreEntry { category: "行為", name: "舔腳", id: "13r" },
    GenreEntry { category: "行為", name: "喝尿", id: "14v" },
    GenreEntry { category: "行為", name: "口交", id: "gre083" },
    GenreEntry { category: "行為", name: "內射", id: "gre084" },
    GenreEntry { category: "行為", name: "自慰", id: "gre085" },
    GenreEntry { category: "行為", name: "後入", id: "gre086" },
    GenreEntry { category: "行為", name: "騎乘位", id: "gre087" },
    GenreEntry { category: "行為", name: "顏射", id: "gre088" },
    GenreEntry { category: "行為", name: "口內射精", id: "gre089" },
    GenreEntry { category: "行為", name: "手淫", id: "gre090" },
    GenreEntry { category: "行為", name: "潮吹", id: "gre091" },
    GenreEntry { category: "行為", name: "輪姦", id: "gre092" },
    GenreEntry { category: "行為", name: "亂交", id: "gre093" },
    GenreEntry { category: "行為", name: "乳交", id: "gre094" },
    GenreEntry { category: "行為", name: "小便", id: "gre095" },
    GenreEntry { category: "行為", name: "吸精", id: "gre096" },
    GenreEntry { category: "行為", name: "深膚色", id: "gre097" },
    GenreEntry { category: "行為", name: "指法", id: "gre098" },
    GenreEntry { category: "行為", name: "騎在臉上", id: "gre099" },
    GenreEntry { category: "行為", name: "連續內射", id: "gre100" },
    GenreEntry { category: "行為", name: "打樁機", id: "gre101" },
    GenreEntry { category: "行為", name: "肛交", id: "gre102" },
    GenreEntry { category: "行為", name: "吞精", id: "gre103" },
    GenreEntry { category: "行為", name: "鴨嘴", id: "gre104" },
    GenreEntry { category: "行為", name: "打飛機", id: "gre105" },
    GenreEntry { category: "行為", name: "剃毛", id: "gre106" },
    GenreEntry { category: "行為", name: "站立位", id: "gre107" },
    GenreEntry { category: "行為", name: "高潮", id: "gre108" },
    GenreEntry { category: "行為", name: "二穴同入", id: "gre109" },
    GenreEntry { category: "行為", name: "舔肛", id: "gre110" },
    GenreEntry { category: "行為", name: "多人口交", id: "gre111" },
    GenreEntry { category: "行為", name: "痙攣", id: "gre112" },
    GenreEntry { category: "行為", name: "玩弄肛門", id: "gre113" },
    GenreEntry { category: "行為", name: "立即口交", id: "gre114" },
    GenreEntry { category: "行為", name: "舔蛋蛋", id: "gre115" },
    GenreEntry { category: "行為", name: "口射", id: "gre116" },
    GenreEntry { category: "行為", name: "陰屁", id: "gre117" },
    GenreEntry { category: "行為", name: "失禁", id: "gre118" },
    GenreEntry { category: "行為", name: "大量潮吹", id: "gre119" },
    GenreEntry { category: "行為", name: "69", id: "gre154" },
    // 玩法
    GenreEntry { category: "玩法", name: "振動", id: "6" },
    GenreEntry { category: "玩法", name: "搭訕", id: "w" },
    GenreEntry { category: "玩法", name: "奴役", id: "28" },
    GenreEntry { category: "玩法", name: "打屁股", id: "10u" },
    GenreEntry { category: "玩法", name: "潤滑油", id: "1c2" },
    GenreEntry { category: "玩法", name: "按摩", id: "6w" },
    GenreEntry { category: "玩法", name: "散步", id: "iz" },
    GenreEntry { category: "玩法", name: "扯破連褲襪", id: "117" },
    GenreEntry { category: "玩法", name: "手銬", id: "zk" },
    GenreEntry { category: "玩法", name: "束縛", id: "22" },
    GenreEntry { category: "玩法", name: "調教", id: "6t" },
    GenreEntry { category: "玩法", name: "假陽具", id: "62" },
    GenreEntry { category: "玩法", name: "變態遊戲", id: "wo" },
    GenreEntry { category: "玩法", name: "注視", id: "8e" },
    GenreEntry { category: "玩法", name: "蠟燭", id: "161" },
    GenreEntry { category: "玩法", name: "電鑽", id: "12u" },
    GenreEntry { category: "玩法", name: "亂搞", id: "kr" },
    GenreEntry { category: "玩法", name: "摩擦", id: "b6" },
    GenreEntry { category: "玩法", name: "項圈", id: "yk" },
    GenreEntry { category: "玩法", name: "繩子", id: "sl" },
    GenreEntry { category: "玩法", name: "灌腸", id: "10w" },
    GenreEntry { category: "玩法", name: "監禁", id: "162" },
    GenreEntry { category: "玩法", name: "車震", id: "2g" },
    GenreEntry { category: "玩法", name: "鞭打", id: "15z" },
    GenreEntry { category: "玩法", name: "懸掛", id: "11i" },
    GenreEntry { category: "玩法", name: "喝口水", id: "1cv" },
    GenreEntry { category: "玩法", name: "精液塗抹", id: "11s" },
    GenreEntry { category: "玩法", name: "舔耳朵", id: "12a" },
    GenreEntry { category: "玩法", name: "女體盛", id: "14l" },
    GenreEntry { category: "玩法", name: "便利店", id: "rk" },
    GenreEntry { category: "玩法", name: "插兩根", id: "11l" },
    GenreEntry { category: "玩法", name: "開口器", id: "125" },
    GenreEntry { category: "玩法", name: "暴露", id: "we" },
    GenreEntry { category: "玩法", name: "陰道放入食物", id: "122" },
    GenreEntry { category: "玩法", name: "大便", id: "10q" },
    GenreEntry { category: "玩法", name: "經期", id: "1b8" },
    GenreEntry { category: "玩法", name: "惡作劇", id: "m3" },
    GenreEntry { category: "玩法", name: "電動按摩器", id: "gre120" },
    GenreEntry { category: "玩法", name: "凌辱", id: "gre121" },
    GenreEntry { category: "玩法", name: "玩具", id: "gre122" },
    GenreEntry { category: "玩法", name: "露出", id: "gre123" },
    GenreEntry { category: "玩法", name: "肛門", id: "gre124" },
    GenreEntry { category: "玩法", name: "拘束", id: "gre125" },
    GenreEntry { category: "玩法", name: "多P", id: "gre126" },
    GenreEntry { category: "玩法", name: "潤滑劑", id: "gre127" },
    GenreEntry { category: "玩法", name: "攝影", id: "gre128" },
    GenreEntry { category: "玩法", name: "野外", id: "gre129" },
    GenreEntry { category: "玩法", name: "陰道觀察", id: "gre130" },
    GenreEntry { category: "玩法", name: "SM", id: "gre131" },
    GenreEntry { category: "玩法", name: "灌入精液", id: "gre132" },
    GenreEntry { category: "玩法", name: "受虐", id: "gre133" },
    GenreEntry { category: "玩法", name: "綁縛", id: "gre134" },
    GenreEntry { category: "玩法", name: "偷拍", id: "gre135" },
    GenreEntry { category: "玩法", name: "異物插入", id: "gre136" },
    GenreEntry { category: "玩法", name: "電話", id: "gre137" },
    GenreEntry { category: "玩法", name: "公寓", id: "gre138" },
    GenreEntry { category: "玩法", name: "遠程操作", id: "gre139" },
    GenreEntry { category: "玩法", name: "偷窺", id: "gre140" },
    GenreEntry { category: "玩法", name: "踩踏", id: "gre141" },
    GenreEntry { category: "玩法", name: "無套", id: "gre164" },
    // 其他
    GenreEntry { category: "其他", name: "企劃物", id: "1z" },
    GenreEntry { category: "其他", name: "獨佔動畫", id: "2a" },
    GenreEntry { category: "其他", name: "10代", id: "1x" },
    GenreEntry { category: "其他", name: "1080p", id: "1j" },
    GenreEntry { category: "其他", name: "人氣系列", id: "2d" },
    GenreEntry { category: "其他", name: "60fps", id: "1k" },
    GenreEntry { category: "其他", name: "超VIP", id: "1f" },
    GenreEntry { category: "其他", name: "投稿", id: "163" },
    GenreEntry { category: "其他", name: "VIP", id: "16" },
    GenreEntry { category: "其他", name: "椅子", id: "102" },
    GenreEntry { category: "其他", name: "風格出眾", id: "3y" },
    GenreEntry { category: "其他", name: "首次作品", id: "40" },
    GenreEntry { category: "其他", name: "更衣室", id: "178" },
    GenreEntry { category: "其他", name: "下午", id: "io" },
    GenreEntry { category: "其他", name: "KTV", id: "1dg" },
    GenreEntry { category: "其他", name: "白天", id: "gre142" },
    GenreEntry { category: "其他", name: "最佳合集", id: "gre143" },
    GenreEntry { category: "其他", name: "VR", id: "gre162" },
    GenreEntry { category: "其他", name: "動漫", id: "gre165" },
    // 場景
    GenreEntry { category: "場景", name: "酒店", id: "2o" },
    GenreEntry { category: "場景", name: "密室", id: "6e" },
    GenreEntry { category: "場景", name: "車", id: "30" },
    GenreEntry { category: "場景", name: "床", id: "103" },
    GenreEntry { category: "場景", name: "陽台", id: "140" },
    GenreEntry { category: "場景", name: "公園", id: "4m" },
    GenreEntry { category: "場景", name: "家中", id: "e7" },
    GenreEntry { category: "場景", name: "公交車", id: "o8" },
    GenreEntry { category: "場景", name: "公司", id: "4z" },
    GenreEntry { category: "場景", name: "門口", id: "po" },
    GenreEntry { category: "場景", name: "附近", id: "he" },
    GenreEntry { category: "場景", name: "學校", id: "7k" },
    GenreEntry { category: "場景", name: "辦公室", id: "59" },
    GenreEntry { category: "場景", name: "樓梯", id: "wj" },
    GenreEntry { category: "場景", name: "住宅", id: "zu" },
    GenreEntry { category: "場景", name: "公共廁所", id: "zj" },
    GenreEntry { category: "場景", name: "旅館", id: "7w" },
    GenreEntry { category: "場景", name: "教室", id: "7j" },
    GenreEntry { category: "場景", name: "廚房", id: "h1" },
    GenreEntry { category: "場景", name: "桌子", id: "x4" },
    GenreEntry { category: "場景", name: "大街", id: "hb" },
    GenreEntry { category: "場景", name: "農村", id: "fz" },
    GenreEntry { category: "場景", name: "和室", id: "6f" },
    GenreEntry { category: "場景", name: "地下室", id: "13k" },
    GenreEntry { category: "場景", name: "牢籠", id: "11w" },
    GenreEntry { category: "場景", name: "屋頂", id: "wh" },
    GenreEntry { category: "場景", name: "游泳池", id: "3a" },
    GenreEntry { category: "場景", name: "電梯", id: "5e" },
    GenreEntry { category: "場景", name: "拍攝現場", id: "vf" },
    GenreEntry { category: "場景", name: "別墅", id: "9p" },
    GenreEntry { category: "場景", name: "房間", id: "gre144" },
    GenreEntry { category: "場景", name: "愛情旅館", id: "gre145" },
    GenreEntry { category: "場景", name: "車內", id: "gre146" },
    GenreEntry { category: "場景", name: "沙發", id: "gre147" },
    GenreEntry { category: "場景", name: "浴室", id: "gre148" },
    GenreEntry { category: "場景", name: "廁所", id: "gre149" },
    GenreEntry { category: "場景", name: "溫泉", id: "gre150" },
    GenreEntry { category: "場景", name: "醫院", id: "gre151" },
    GenreEntry { category: "場景", name: "榻榻米", id: "gre152" },
];

// ─── 平铺查找表（从原始数据构建） ───

fn build_lookup(entries: &[GenreEntry]) -> HashMap<&'static str, &'static str> {
    let mut map = HashMap::with_capacity(entries.len());
    for e in entries {
        map.insert(e.name, e.id);
    }
    map
}

static CENSORED_LOOKUP: LazyLock<HashMap<&'static str, &'static str>> =
    LazyLock::new(|| build_lookup(CENSORED_ENTRIES));

static UNCENSORED_LOOKUP: LazyLock<HashMap<&'static str, &'static str>> =
    LazyLock::new(|| build_lookup(UNCENSORED_ENTRIES));

// ─── 分组输出（供前端展示） ───

/// 将有码+无码分类分别按大类别分组返回。
pub fn all_genre_groups() -> JavbusGenreData {
    fn build_groups(entries: &[GenreEntry]) -> Vec<GenreGroup> {
        let mut seen_cats: Vec<&str> = Vec::new();
        let mut cat_map: HashMap<&str, Vec<&str>> = HashMap::new();
        for e in entries {
            let names = cat_map.entry(e.category).or_default();
            if !names.contains(&e.name) {
                if !seen_cats.contains(&e.category) {
                    seen_cats.push(e.category);
                }
                names.push(e.name);
            }
        }
        let mut groups = Vec::new();
        for cat in &seen_cats {
            if let Some(names) = cat_map.remove(cat) {
                let mut sorted: Vec<String> = names.into_iter().map(|s| s.to_string()).collect();
                sorted.sort_unstable_by(|a, b| a.cmp(b));
                groups.push(GenreGroup {
                    category: cat.to_string(),
                    genres: sorted,
                });
            }
        }
        groups
    }

    JavbusGenreData {
        censored: build_groups(CENSORED_ENTRIES),
        uncensored: build_groups(UNCENSORED_ENTRIES),
    }
}

/// 返回全部硬编码 JavBus 分类名（有码+无码合并去重），供前端发现页展示（兼容旧接口）。
pub fn all_genre_names() -> Vec<&'static str> {
    let mut names: Vec<&str> = CENSORED_LOOKUP.keys().copied().collect();
    for k in UNCENSORED_LOOKUP.keys() {
        if !CENSORED_LOOKUP.contains_key(k) {
            names.push(k);
        }
    }
    names.sort_unstable_by(|a, b| a.cmp(b));
    names
}

// ─── 简繁映射 ───

static SIMP_TO_TRAD: LazyLock<HashMap<char, char>> = LazyLock::new(|| {
    HashMap::from([
        ('丝', '絲'),
        ('袜', '襪'),
        ('恋', '戀'),
        ('语', '語'),
        ('妇', '婦'),
        ('发', '發'),
        ('电', '電'),
        ('车', '車'),
        ('轮', '輪'),
        ('奸', '姦'),
        ('药', '藥'),
        ('紧', '緊'),
        ('缚', '縛'),
        ('监', '監'),
        ('异', '異'),
        ('物', '物'),
        ('强', '強'),
        ('乱', '亂'),
        ('伦', '倫'),
        ('学', '學'),
        ('体', '體'),
        ('内', '內'),
        ('无', '無'),
        ('毛', '毛'),
        ('画', '畫'),
        ('质', '質'),
        ('戏', '戲'),
        ('剧', '劇'),
        ('独', '獨'),
        ('立', '立'),
        ('制', '製'),
        ('作', '作'),
        ('合', '合'),
        ('集', '集'),
        ('业', '業'),
        ('余', '餘'),
        ('导', '導'),
        ('演', '演'),
        ('护', '護'),
        ('士', '士'),
        ('秘', '秘'),
        ('书', '書'),
        ('医', '醫'),
        ('生', '生'),
        ('妈', '媽'),
        ('爷', '爺'),
        ('奶', '奶'),
        ('孙', '孫'),
        ('儿', '兒'),
        ('员', '員'),
        ('队', '隊'),
        ('长', '長'),
        ('门', '門'),
        ('开', '開'),
        ('关', '關'),
        ('风', '風'),
        ('险', '險'),
        ('马', '馬'),
        ('鱼', '魚'),
        ('鸟', '鳥'),
        ('龙', '龍'),
        ('龟', '龜'),
        ('动', '動'),
        ('节', '節'),
        ('页', '頁'),
        ('飞', '飛'),
        ('齐', '齊'),
        ('齿', '齒'),
        ('转', '轉'),
        ('变', '變'),
        ('为', '為'),
        ('录', '錄'),
        ('实', '實'),
        ('阴', '陰'),
        ('阳', '陽'),
        ('单', '單'),
        ('杀', '殺'),
        ('梦', '夢'),
        ('爱', '愛'),
        ('盗', '盜'),
        ('摄', '攝'),
        ('罗', '羅'),
        ('丽', '麗'),
        ('亚', '亞'),
        ('欧', '歐'),
        ('兰', '蘭'),
        ('岁', '歲'),
        ('远', '遠'),
        ('岛', '島'),
        ('对', '對'),
        ('写', '寫'),
        ('真', '真'),
        ('乐', '樂'),
        ('机', '機'),
        ('铁', '鐵'),
        ('众', '眾'),
        ('传', '傳'),
        ('尔', '爾'),
        ('击', '擊'),
        ('标', '標'),
        ('枪', '槍'),
        ('担', '擔'),
        ('据', '據'),
        ('扩', '擴'),
        ('扫', '掃'),
        ('拟', '擬'),
        ('签', '簽'),
        ('续', '續'),
        ('线', '線'),
        ('网', '網'),
        ('络', '絡'),
        ('码', '碼'),
        ('针', '針'),
        ('错', '錯'),
        ('键', '鍵'),
        ('镜', '鏡'),
        ('链', '鏈'),
        ('颜', '顏'),
    ])
});

fn to_traditional(s: &str) -> String {
    s.chars().map(|c| SIMP_TO_TRAD.get(&c).copied().unwrap_or(c)).collect()
}

/// 在硬编码查找表中定位分类的 source_id。
pub fn lookup_genre_source_id(name: &str, lane: Lane) -> Option<&'static str> {
    let name = name.trim();
    if name.is_empty() {
        return None;
    }

    let table: &HashMap<&str, &str> = match lane {
        Lane::Censored => &CENSORED_LOOKUP,
        Lane::Uncensored => &UNCENSORED_LOOKUP,
    };

    if let Some(id) = table.get(name) {
        return Some(id);
    }

    let traditional = to_traditional(name);
    if traditional != name {
        if let Some(id) = table.get(traditional.as_str()) {
            return Some(id);
        }
    }

    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn exact_match_censored() {
        assert_eq!(lookup_genre_source_id("ストッキング", Lane::Censored), Some("hn"));
        assert_eq!(lookup_genre_source_id("巨乳", Lane::Censored), Some("e"));
        assert_eq!(lookup_genre_source_id("中出", Lane::Censored), Some("4"));
    }

    #[test]
    fn simplified_to_traditional_match() {
        assert_eq!(lookup_genre_source_id("顏射", Lane::Censored), Some("n"));
    }

    #[test]
    fn not_found_returns_none() {
        assert_eq!(lookup_genre_source_id("不存在的分类xyz", Lane::Censored), None);
    }

    #[test]
    fn empty_name_returns_none() {
        assert_eq!(lookup_genre_source_id("", Lane::Censored), None);
    }

    #[test]
    fn groups_have_categories() {
        let data = all_genre_groups();
        assert!(!data.censored.is_empty());
        assert!(!data.uncensored.is_empty());
        for g in &data.censored {
            assert!(!g.category.is_empty());
            assert!(!g.genres.is_empty());
        }
        for g in &data.uncensored {
            assert!(!g.category.is_empty());
            assert!(!g.genres.is_empty());
        }
    }
}
